// Bundle a subset of level JSONs into a single ES module so esbuild can
// inline them into the wx-game main bundle. WX mini-game main packages
// cap at 4 MB; we ship a small playable subset here and leave subpackage
// streaming to a follow-up.

import { readdir, readFile, writeFile, mkdir } from "node:fs/promises";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(__dirname, "../../../..");
const LEVELS_DIR = resolve(ROOT, "levels_neutral");
const OUT_FILE = resolve(__dirname, "../src/levels.generated.ts");
const LIMIT = Number(process.env.WXGAME_LEVEL_LIMIT ?? "50");

const files = (await readdir(LEVELS_DIR))
  .filter((f) => f.endsWith(".json"))
  .sort();

const picked = files.slice(0, LIMIT);
const entries = [];
for (const f of picked) {
  const raw = JSON.parse(await readFile(resolve(LEVELS_DIR, f), "utf8"));
  entries.push({ key: f, raw });
}

await mkdir(dirname(OUT_FILE), { recursive: true });
const body =
  `// AUTO-GENERATED by scripts/build-levels.mjs — do not edit by hand.\n` +
  `import type { RawLevelFile } from "@ea/core";\n\n` +
  `export interface BundledLevel { key: string; raw: RawLevelFile; }\n\n` +
  `export const BUNDLED_LEVELS: BundledLevel[] = ${JSON.stringify(entries, null, 0)};\n`;

await writeFile(OUT_FILE, body, "utf8");
console.log(`wrote ${picked.length} levels to ${OUT_FILE}`);
