// Generate the TS module the main wxgame bundle imports.
//
// Emits a single `src/levels.generated.ts` exporting:
//   MAIN_LEVELS — compact-form levels embedded in the main package
//   ALL_KEYS    — every level key in sort order (for the picker / nav)
//   KEY_TO_LOC  — key → [packIdx, localIdx]; packIdx === -1 means MAIN_LEVELS
//   PACK_COUNT  — total number of subpackages

import { mkdir, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { chunkLevels, readAllLevels } from "./_encode.mjs";

const __dirname = dirname(fileURLToPath(import.meta.url));
const OUT_FILE = resolve(__dirname, "../src/levels.generated.ts");

const all = await readAllLevels();
const { main, packs, locator, allKeys } = chunkLevels(all);

await mkdir(dirname(OUT_FILE), { recursive: true });
const body =
  `// AUTO-GENERATED by scripts/build-levels.mjs — do not edit by hand.\n` +
  `// Compact level: [W, H, [[fdir, ...cellIdx], ...]]\n` +
  `// fdir: 0=+x 1=+y 2=-x 3=-y; cellIdx = y*W+x.\n\n` +
  `export type CompactLevel = [number, number, number[][]];\n` +
  `export interface MainLevel { key: string; data: CompactLevel; }\n\n` +
  `export const MAIN_LEVELS: MainLevel[] = ${JSON.stringify(
    main.map((e) => ({ key: e.key, data: e.encoded })),
    null,
    0,
  )};\n\n` +
  `export const ALL_KEYS: string[] = ${JSON.stringify(allKeys, null, 0)};\n\n` +
  `export const KEY_TO_LOC: Record<string, [number, number]> = ${JSON.stringify(
    locator,
    null,
    0,
  )};\n\n` +
  `export const PACK_COUNT = ${packs.length};\n`;

await writeFile(OUT_FILE, body, "utf8");
console.log(`wrote ${main.length} main levels + ${packs.length} pack manifests to ${OUT_FILE}`);
