// Generate the level catalog the H5 bundle uses, mirroring wxgame's
// build-levels.mjs but emitting JSON packs for runtime fetch() instead of
// JS subpackages.
//
// Outputs:
//   src/levels.generated.ts       — MAIN_LEVELS / ALL_KEYS / KEY_TO_LOC / PACK_COUNT
//   public/packs/packN.json       — compact-encoded level chunk (static asset)
//
// Same MAIN_BUNDLE_LIMIT (30) and PACK_SIZE (300) as wxgame so both
// targets stay aligned. Reuses the shared encoder.

import { mkdir, rm, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { chunkLevels, readAllLevels } from "../../wxgame/scripts/_encode.mjs";

const __dirname = dirname(fileURLToPath(import.meta.url));
const PKG_ROOT = resolve(__dirname, "..");
const TS_OUT = resolve(PKG_ROOT, "src/levels.generated.ts");
const PACKS_DIR = resolve(PKG_ROOT, "public/packs");

const all = await readAllLevels();
const { main, packs, locator, allKeys } = chunkLevels(all);

// 1. TS catalog (consumed by Vite)
await mkdir(dirname(TS_OUT), { recursive: true });
const body =
  `// AUTO-GENERATED by scripts/build-levels.mjs — do not edit by hand.\n\n` +
  `import type { CompactLevel } from "@ea/core";\n\n` +
  `export interface MainLevel { key: string; data: CompactLevel; }\n\n` +
  `export const MAIN_LEVELS: MainLevel[] = ${JSON.stringify(
    main.map((e) => ({ key: e.key, data: e.encoded })),
    null,
    0,
  )};\n\n` +
  `export const ALL_KEYS: string[] = ${JSON.stringify(allKeys, null, 0)};\n\n` +
  `export const KEY_TO_LOC: Record<string, [number, number]> = ${JSON.stringify(
    locator,
    null,
    0,
  )};\n\n` +
  `export const PACK_COUNT = ${packs.length};\n`;
await writeFile(TS_OUT, body, "utf8");

// 2. Pack JSON files served from public/packs/
await rm(PACKS_DIR, { recursive: true, force: true });
await mkdir(PACKS_DIR, { recursive: true });
for (let p = 0; p < packs.length; p++) {
  const payload = packs[p].map((e) => ({ key: e.key, data: e.encoded }));
  await writeFile(resolve(PACKS_DIR, `pack${p}.json`), JSON.stringify(payload), "utf8");
}

console.log(
  `wrote ${main.length} main levels + ${packs.length} pack JSON files` +
    ` (TS → ${TS_OUT}, packs → ${PACKS_DIR})`,
);
