import {
  type CompactLevel,
  createGame,
  decodeCompact,
  ensureShuffleSeed,
  findArrowAt,
  findNextMove,
  type GameSnapshot,
  type GameState,
  loadLevel,
  loadProgress,
  type Progress,
  type ProgressStorage,
  resetGame,
  restoreGame,
  saveProgress,
  shuffleByDifficulty,
  snapshotGame,
  tryPull,
  validateLevel,
} from "@ea/core";
import {
  type AudioContextLike,
  drawGame,
  drawWinOverlay,
  fitView,
  hitTestOverlay,
  makeSynth,
  type OverlayHitbox,
  pickCell,
  type Synth,
} from "@ea/renderer";
import { ALL_KEYS, KEY_TO_LOC, MAIN_LEVELS, PACK_COUNT } from "./levels.generated.js";
import {
  addLives,
  getConfig as getLivesConfig,
  getState as getLivesState,
  nextRegenMs,
  subscribe as subscribeLives,
  tickNow as tickLives,
  tryConsume as tryConsumeLife,
} from "./lives-store.js";

// --- animation state ---------------------------------------------------------

interface Tween {
  from: number;
  to: number;
  start: number;
  dur: number;
  escapedAtEnd: boolean;
}
interface Shake {
  start: number;
  dur: number;
  ax: number;
  ay: number;
}

const tweens = new Map<number, Tween>();
const shakes = new Map<number, Shake>();
let rafId = 0;

function easeOutCubic(u: number): number {
  return 1 - (1 - u) ** 3;
}

function evalTween(tw: Tween, now: number): number {
  const u = Math.min(1, Math.max(0, (now - tw.start) / tw.dur));
  return tw.from + (tw.to - tw.from) * easeOutCubic(u);
}

function startTween(id: number, before: number, after: number, escapedAtEnd: boolean): void {
  const now = performance.now();
  const existing = tweens.get(id);
  const fromNow = existing ? evalTween(existing, now) : before;
  const dist = Math.abs(after - fromNow);
  const dur = Math.min(450, Math.max(120, dist * 70));
  tweens.set(id, { from: fromNow, to: after, start: now, dur, escapedAtEnd });
  ensureRAF();
}

function startShake(id: number, facing: { x: number; y: number }): void {
  shakes.set(id, {
    start: performance.now(),
    dur: 220,
    ax: facing.x,
    ay: facing.y,
  });
  ensureRAF();
}

function evalShake(sh: Shake, now: number, cell: number): { dx: number; dy: number } | null {
  const u = (now - sh.start) / sh.dur;
  if (u >= 1) return null;
  const amp = cell * 0.22 * (1 - u);
  const w = Math.sin(u * Math.PI * 5);
  return { dx: sh.ax * amp * w, dy: sh.ay * amp * w };
}

function ensureRAF(): void {
  if (rafId) return;
  const step = (): void => {
    rafId = 0;
    render();
    if (tweens.size > 0 || shakes.size > 0 || isWinAnimating() || isHintActive()) {
      rafId = requestAnimationFrame(step);
    } else if (hintArrowId != null) {
      // Hint timed out — clear and repaint once without the halo.
      hintArrowId = null;
      render();
    }
  };
  rafId = requestAnimationFrame(step);
}

function isAnimating(): boolean {
  return tweens.size > 0;
}

function isWinAnimating(): boolean {
  return winStart != null && performance.now() - winStart < 700;
}

function clearAnimations(): void {
  tweens.clear();
  shakes.clear();
}

// --- audio synthesis ---------------------------------------------------------

const audioCtx: AudioContextLike | null = (() => {
  try {
    const Ctor =
      window.AudioContext ||
      (window as unknown as { webkitAudioContext?: typeof AudioContext }).webkitAudioContext;
    if (!Ctor) return null;
    return new Ctor() as unknown as AudioContextLike;
  } catch {
    return null;
  }
})();
const synth: Synth = makeSynth(audioCtx);

// --- win overlay state -------------------------------------------------------

let winStart: number | null = null;
let winHitbox: OverlayHitbox | null = null;

// --- level entries ----------------------------------------------------------
//
// The catalog (`ALL_KEYS` + `KEY_TO_LOC` + `MAIN_LEVELS`) is generated by
// scripts/build-levels.mjs and committed only to-memory at build time. The
// picker shows every entry parsed from the filename; the actual level data
// (compact form) for keys outside MAIN_LEVELS is fetched on demand from
// /packs/packN.json and decoded back into a RawLevelFile.

interface Entry {
  key: string;
  name: string;
  size?: string;
  count?: number;
  tags: string[];
}

function parseEntry(key: string): Entry {
  const name = key.replace(/^\d+__/, "").replace(/\.json$/, "");
  let size: string | undefined;
  let count: number | undefined;
  let tags: string[] = [];
  for (const m of name.matchAll(/\[([^\]]+)\]/g)) {
    const g = m[1]!;
    if (/^\d+x\d+$/.test(g)) size = g;
    else if (/^\d+$/.test(g)) count = Number(g);
    else if (/[A-Za-z]/.test(g)) tags = g.split(",").map((s) => s.trim());
  }
  return { key, name, size, count, tags };
}

// Order is computed lazily: we need progress.shuffleSeed first, which lives
// further down. See "ordering" section below where ORDERED_KEYS is produced.

// --- compact-level lookup ---------------------------------------------------

const mainByKey = new Map<string, CompactLevel>();
for (const lvl of MAIN_LEVELS) mainByKey.set(lvl.key, lvl.data);

interface PackEntry {
  key: string;
  data: CompactLevel;
}

const packCache = new Map<number, PackEntry[]>();
const packInflight = new Map<number, Promise<PackEntry[]>>();

async function loadPack(packIdx: number): Promise<PackEntry[]> {
  const cached = packCache.get(packIdx);
  if (cached) return cached;
  const existing = packInflight.get(packIdx);
  if (existing) return existing;
  const p = fetch(`${import.meta.env.BASE_URL}packs/pack${packIdx}.json`)
    .then((r) => {
      if (!r.ok) throw new Error(`pack${packIdx} HTTP ${r.status}`);
      return r.json() as Promise<PackEntry[]>;
    })
    .then((data) => {
      packCache.set(packIdx, data);
      return data;
    });
  packInflight.set(packIdx, p);
  p.finally(() => packInflight.delete(packIdx));
  return p;
}

async function resolveLevel(key: string): Promise<CompactLevel | null> {
  const main = mainByKey.get(key);
  if (main) return main;
  const loc = KEY_TO_LOC[key];
  if (!loc) return null;
  const [packIdx, localIdx] = loc;
  if (packIdx < 0) return null;
  const pack = await loadPack(packIdx);
  return pack[localIdx]?.data ?? null;
}

void PACK_COUNT;

// --- persistence ------------------------------------------------------------

const STORAGE_KEY = "escape_arrows_progress";

const storage: ProgressStorage = {
  read: () => {
    try {
      return localStorage.getItem(STORAGE_KEY);
    } catch {
      return null;
    }
  },
  write: (v) => {
    try {
      localStorage.setItem(STORAGE_KEY, v);
    } catch {
      // quota / privacy mode — just lose progress
    }
  },
};

const progress: Progress = loadProgress(storage);

function persist(): void {
  saveProgress(storage, progress);
}

// --- ordering ---------------------------------------------------------------
//
// shuffleByDifficulty groups ALL_KEYS into difficulty quantiles (bucket
// sequence ascending) and deterministically shuffles within each bucket
// using a per-user seed. Seed is minted on first launch and persisted so
// returning players see a stable order.

const shuffleSeed = ensureShuffleSeed(progress);
persist();
const ORDERED_KEYS = shuffleByDifficulty(ALL_KEYS, shuffleSeed);

const entries: Entry[] = ORDERED_KEYS.map(parseEntry);
const allTags = [...new Set(entries.flatMap((e) => e.tags))].sort();

// --- DOM refs ---------------------------------------------------------------

const showPathsBox = document.getElementById("show-paths") as HTMLInputElement;
const meta = document.getElementById("meta") as HTMLSpanElement;
const status = document.getElementById("status") as HTMLSpanElement;
const prevBtn = document.getElementById("prev-btn") as HTMLButtonElement;
const nextBtn = document.getElementById("next-btn") as HTMLButtonElement;
const resetBtn = document.getElementById("reset-btn") as HTMLButtonElement;
const undoBtn = document.getElementById("undo-btn") as HTMLButtonElement;
const hintBtn = document.getElementById("hint-btn") as HTMLButtonElement;
const canvas = document.getElementById("board") as HTMLCanvasElement;
const ctx = canvas.getContext("2d")!;

const livesHearts = document.getElementById("lives-hearts") as HTMLSpanElement;
const livesTimer = document.getElementById("lives-timer") as HTMLSpanElement;
const noLivesDialog = document.getElementById("no-lives-dialog") as HTMLDivElement;
const nlTimer = document.getElementById("nl-timer") as HTMLParagraphElement;
const nlAdBtn = document.getElementById("nl-ad-btn") as HTMLButtonElement;
const nlCloseBtn = document.getElementById("nl-close-btn") as HTMLButtonElement;

const pickerBtn = document.getElementById("picker-btn") as HTMLButtonElement;
const pickerLabel = document.getElementById("picker-label") as HTMLSpanElement;
const pickerPanel = document.getElementById("picker-panel") as HTMLDivElement;
const pickerSearch = document.getElementById("picker-search") as HTMLInputElement;
const pickerCount = document.getElementById("picker-count") as HTMLSpanElement;
const pickerClose = document.getElementById("picker-close") as HTMLButtonElement;
const pickerTags = document.getElementById("picker-tags") as HTMLDivElement;
const pickerList = document.getElementById("picker-list") as HTMLDivElement;

let game: GameState | null = null;
let currentKey: string | null = null;
let loadingKey: string | null = null;

// Undo / hint state ---------------------------------------------------------
const UNDO_CAP = 20;
const undoStack: GameSnapshot[] = [];
let hintArrowId: number | null = null;
let hintStart = 0;
const HINT_DURATION = 2500; // ms before highlight auto-fades

function clearUndoStack(): void {
  undoStack.length = 0;
  refreshHistoryControls();
}

function clearHint(): void {
  if (hintArrowId == null) return;
  hintArrowId = null;
  render();
}

function refreshHistoryControls(): void {
  undoBtn.disabled = undoStack.length === 0;
  hintBtn.disabled = !game || game.status !== "playing" || loadingKey != null;
}

function isHintActive(): boolean {
  return hintArrowId != null && performance.now() - hintStart < HINT_DURATION;
}

function dpr(): number {
  return Math.min(window.devicePixelRatio || 1, 2);
}

function viewSize(): { w: number; h: number } {
  const d = dpr();
  return { w: canvas.width / d, h: canvas.height / d };
}

function resize(): void {
  const d = dpr();
  const rect = canvas.getBoundingClientRect();
  canvas.width = Math.floor(rect.width * d);
  canvas.height = Math.floor(rect.height * d);
  ctx.setTransform(d, 0, 0, d, 0, 0);
  render();
}

function render(): void {
  if (!game) return;
  const { w, h } = viewSize();
  const t = fitView(game.level, w, h);

  const now = performance.now();
  const progressOverride = new Map<number, number>();
  const drawEscapedIds = new Set<number>();
  for (const [id, tw] of tweens) {
    progressOverride.set(id, evalTween(tw, now));
    if (now >= tw.start + tw.dur) {
      tweens.delete(id);
    } else if (tw.escapedAtEnd) {
      drawEscapedIds.add(id);
    }
  }
  const shakeOffsets = new Map<number, { dx: number; dy: number }>();
  for (const [id, sh] of shakes) {
    const off = evalShake(sh, now, t.cell);
    if (!off) {
      shakes.delete(id);
      continue;
    }
    shakeOffsets.set(id, off);
  }

  let highlightArrowId: number | null = null;
  let highlightPulse = 1;
  if (isHintActive()) {
    highlightArrowId = hintArrowId;
    const u = (performance.now() - hintStart) / HINT_DURATION;
    // 0.55 + 0.45*sin gives a perceptible but non-flickery pulse; fade tail.
    const pulseAmp = 0.55 + 0.45 * Math.sin(performance.now() * 0.012);
    const fade = u < 0.8 ? 1 : Math.max(0, 1 - (u - 0.8) / 0.2);
    highlightPulse = pulseAmp * fade;
  }

  drawGame(ctx as any, game, t, {
    showPaths: showPathsBox.checked,
    progressOverride,
    shakeOffsets,
    drawEscapedIds,
    highlightArrowId,
    highlightPulse,
  });

  if (game.status === "won" && winStart != null) {
    const phase = (performance.now() - winStart) / 1000;
    winHitbox = drawWinOverlay(ctx as any, w, h, phase);
  } else {
    winHitbox = null;
  }
}

function updateStatus(): void {
  if (loadingKey != null) {
    status.textContent = "加载中…";
    status.style.color = "#94a3b8";
    return;
  }
  if (!game) {
    status.textContent = "";
    return;
  }
  const remaining = game.arrows.filter((a) => !a.escaped).length;
  if (game.status === "won") {
    status.textContent = "通关！";
    status.style.color = "#22c55e";
  } else {
    status.textContent = `剩余 ${remaining}/${game.arrows.length}`;
    status.style.color = "#e2e8f0";
  }
}

function updatePickerLabel(): void {
  const entry = entries.find((e) => e.key === currentKey);
  const idx = entry ? entries.indexOf(entry) + 1 : 0;
  pickerLabel.textContent = entry ? `${idx}/${entries.length}  ${entry.name}` : "—";
}

function selectLevel(key: string): void {
  const entry = entries.find((e) => e.key === key);
  if (!entry) return;
  currentKey = key;
  loadingKey = key;
  game = null;
  clearAnimations();
  clearUndoStack();
  hintArrowId = null;
  winStart = null;
  meta.textContent = "加载中…";
  updatePickerLabel();
  updateStatus();
  refreshHistoryControls();
  render();
  resolveLevel(key)
    .then((compact) => {
      if (loadingKey !== key) return; // user moved on already
      if (!compact) {
        meta.textContent = `[关卡缺失] ${key}`;
        loadingKey = null;
        return;
      }
      const level = loadLevel(decodeCompact(compact));
      const err = validateLevel(level);
      meta.textContent = err
        ? `[校验失败] ${err}`
        : `${level.width}×${level.height}  ${level.arrows.length} 箭头`;
      game = createGame(level);
      loadingKey = null;
      progress.lastKey = key;
      persist();
      updateStatus();
      refreshHistoryControls();
      render();
    })
    .catch((e) => {
      if (loadingKey !== key) return;
      meta.textContent = `[加载失败] ${String((e as Error).message ?? e)}`;
      loadingKey = null;
      render();
    });
}

function gotoNextLevel(): void {
  const i = entries.findIndex((e) => e.key === currentKey);
  if (i >= 0 && i < entries.length - 1) selectLevel(entries[i + 1]!.key);
}

function handlePointer(clientX: number, clientY: number): void {
  if (!game) return;
  const rect = canvas.getBoundingClientRect();
  const px = clientX - rect.left;
  const py = clientY - rect.top;

  // Win-overlay button takes priority while the level is won.
  if (game.status === "won" && winHitbox) {
    const hit = hitTestOverlay(winHitbox, px, py);
    if (hit === "next") {
      synth.click();
      gotoNextLevel();
    }
    return;
  }

  if (isAnimating()) return;
  const { w, h } = viewSize();
  const t = fitView(game.level, w, h);
  const cell = pickCell(px, py, t);
  if (cell.x < 0 || cell.y < 0 || cell.x >= game.level.width || cell.y >= game.level.height) {
    return;
  }
  const arrow = findArrowAt(game, cell);
  if (!arrow) return;
  const before = arrow.progress;
  const snap = snapshotGame(game);
  const result = tryPull(game, arrow.id);
  const after = arrow.progress;
  if (result.steps > 0) {
    pushUndo(snap);
    if (hintArrowId === arrow.id) clearHint();
    startTween(arrow.id, before, after, result.escaped);
    if (result.escaped) synth.escape();
    else synth.whoosh(result.steps);
  } else {
    startShake(arrow.id, arrow.data.facing);
    synth.thud();
  }
  if (result.won && currentKey) {
    progress.completed.add(currentKey);
    persist();
    winStart = performance.now();
    synth.win();
    ensureRAF();
  }
  updateStatus();
  refreshHistoryControls();
  render();
}

function pushUndo(snap: GameSnapshot): void {
  undoStack.push(snap);
  if (undoStack.length > UNDO_CAP) undoStack.shift();
  refreshHistoryControls();
}

function doUndo(): void {
  if (!game) return;
  if (loadingKey != null) return;
  if (isAnimating()) return;
  const snap = undoStack.pop();
  if (!snap) return;
  restoreGame(game, snap);
  clearAnimations();
  winStart = null;
  hintArrowId = null;
  synth.click();
  updateStatus();
  refreshHistoryControls();
  render();
}

function doHint(): void {
  if (!game || game.status !== "playing") return;
  if (loadingKey != null || isAnimating()) return;
  hintBtn.disabled = true;
  hintBtn.textContent = "💡 思考…";
  // findNextMove is synchronous; defer one frame so the disabled-state paints
  // before we possibly block for a few hundred ms on a hard level.
  requestAnimationFrame(() => {
    const moveId = game ? findNextMove(game, Date.now() + 2000) : null;
    hintBtn.textContent = "💡 提示";
    if (moveId == null) {
      hintBtn.textContent = "💡 无解";
      setTimeout(() => {
        hintBtn.textContent = "💡 提示";
        refreshHistoryControls();
      }, 1200);
      return;
    }
    hintArrowId = moveId;
    hintStart = performance.now();
    synth.click();
    refreshHistoryControls();
    ensureRAF();
  });
}

// --- picker -----------------------------------------------------------------

const MAX_VISIBLE = 500;
const activeTags = new Set<string>();

function buildTagChips(): void {
  pickerTags.innerHTML = "";
  for (const tag of allTags) {
    const el = document.createElement("span");
    el.className = "picker-tag";
    el.textContent = tag;
    el.addEventListener("click", () => {
      if (activeTags.has(tag)) {
        activeTags.delete(tag);
        el.classList.remove("active");
      } else {
        activeTags.add(tag);
        el.classList.add("active");
      }
      refreshList();
    });
    pickerTags.appendChild(el);
  }
}

function matchEntry(e: Entry, search: string): boolean {
  if (search) {
    const hay = e.key.toLowerCase();
    if (!hay.includes(search)) return false;
  }
  if (activeTags.size > 0) {
    for (const t of activeTags) if (!e.tags.includes(t)) return false;
  }
  return true;
}

function refreshList(): void {
  const search = pickerSearch.value.trim().toLowerCase();
  const matches = entries.filter((e) => matchEntry(e, search));
  pickerCount.textContent = `${matches.length}/${entries.length}`;
  pickerList.innerHTML = "";
  const visible = matches.slice(0, MAX_VISIBLE);
  for (const e of visible) {
    const idx = entries.indexOf(e);
    const row = document.createElement("div");
    row.className = "picker-row" + (e.key === currentKey ? " current" : "");
    const idxEl = document.createElement("span");
    idxEl.className = "picker-idx";
    idxEl.textContent = `#${idx + 1}`;
    const nameEl = document.createElement("span");
    nameEl.className = "picker-name";
    nameEl.textContent = e.name;
    const metaEl = document.createElement("span");
    metaEl.className = "picker-meta";
    const parts: string[] = [];
    if (e.size) parts.push(e.size);
    if (e.count != null) parts.push(`${e.count} 箭`);
    if (e.tags.length > 0) parts.push(e.tags.join(", "));
    metaEl.textContent = parts.join("  ·  ");
    const doneEl = document.createElement("span");
    doneEl.className = "picker-done";
    doneEl.textContent = progress.completed.has(e.key) ? "✓" : "";
    row.append(idxEl, nameEl, metaEl, doneEl);
    row.addEventListener("click", () => {
      closePicker();
      selectLevel(e.key);
    });
    pickerList.appendChild(row);
  }
  if (matches.length > MAX_VISIBLE) {
    const more = document.createElement("div");
    more.className = "picker-more";
    more.textContent = `还有 ${matches.length - MAX_VISIBLE} 项，缩小搜索范围查看全部`;
    pickerList.appendChild(more);
  }
}

function openPicker(): void {
  pickerPanel.hidden = false;
  refreshList();
  pickerSearch.focus();
  pickerSearch.select();
  // Scroll to currently selected entry if visible
  const cur = pickerList.querySelector(".picker-row.current") as HTMLElement | null;
  if (cur) cur.scrollIntoView({ block: "center" });
}

function closePicker(): void {
  pickerPanel.hidden = true;
}

// --- wiring -----------------------------------------------------------------

showPathsBox.addEventListener("change", render);
window.addEventListener("resize", resize);

prevBtn.addEventListener("click", () => {
  const i = entries.findIndex((e) => e.key === currentKey);
  if (i > 0) selectLevel(entries[i - 1]!.key);
});
nextBtn.addEventListener("click", () => {
  const i = entries.findIndex((e) => e.key === currentKey);
  if (i >= 0 && i < entries.length - 1) selectLevel(entries[i + 1]!.key);
});
resetBtn.addEventListener("click", () => {
  if (!game) return;
  if (!tryConsumeLife()) {
    openNoLivesDialog();
    return;
  }
  resetGame(game);
  clearAnimations();
  clearUndoStack();
  hintArrowId = null;
  winStart = null;
  updateStatus();
  refreshHistoryControls();
  render();
});

undoBtn.addEventListener("click", doUndo);
hintBtn.addEventListener("click", doHint);

pickerBtn.addEventListener("click", openPicker);
pickerClose.addEventListener("click", closePicker);
pickerSearch.addEventListener("input", refreshList);
pickerSearch.addEventListener("keydown", (ev) => {
  if (ev.key === "Escape") closePicker();
});
window.addEventListener("keydown", (ev) => {
  if (ev.key === "Escape" && !pickerPanel.hidden) closePicker();
  // Don't steal keystrokes from the picker search input.
  if (document.activeElement === pickerSearch) return;
  if (!pickerPanel.hidden) return;
  if (ev.key === "z" || ev.key === "Z") {
    ev.preventDefault();
    doUndo();
  } else if (ev.key === "h" || ev.key === "H") {
    ev.preventDefault();
    doHint();
  }
});

canvas.addEventListener("click", (ev) => handlePointer(ev.clientX, ev.clientY));
canvas.addEventListener(
  "touchstart",
  (ev) => {
    if (ev.touches.length === 0) return;
    const t = ev.touches[0]!;
    handlePointer(t.clientX, t.clientY);
    ev.preventDefault();
  },
  { passive: false },
);

// --- lives UI ---------------------------------------------------------------

const HEART_FULL = `<svg viewBox="0 0 24 24" width="16" height="16" aria-hidden="true"><path fill="#ef4444" stroke="#7f1d1d" stroke-width="1.2" stroke-linejoin="round" d="M12 20.5s-7.2-4.4-9.2-9.1C1.2 7.2 4.3 3.5 8 4.2c1.7.3 3.1 1.4 4 2.8.9-1.4 2.3-2.5 4-2.8 3.7-.7 6.8 3 5.2 7.2C19.2 16.1 12 20.5 12 20.5Z"/></svg>`;
const HEART_EMPTY = `<svg viewBox="0 0 24 24" width="16" height="16" aria-hidden="true"><path fill="none" stroke="#475569" stroke-width="1.4" stroke-linejoin="round" d="M12 20.5s-7.2-4.4-9.2-9.1C1.2 7.2 4.3 3.5 8 4.2c1.7.3 3.1 1.4 4 2.8.9-1.4 2.3-2.5 4-2.8 3.7-.7 6.8 3 5.2 7.2C19.2 16.1 12 20.5 12 20.5Z"/></svg>`;

function formatMs(ms: number): string {
  const total = Math.max(0, Math.ceil(ms / 1000));
  const m = Math.floor(total / 60);
  const s = total % 60;
  return `${m}:${s.toString().padStart(2, "0")}`;
}

function renderLives(): void {
  tickLives();
  const { lives } = getLivesState();
  const { max } = getLivesConfig();
  const hearts: string[] = [];
  for (let i = 0; i < max; i++) {
    hearts.push(`<span class="heart">${i < lives ? HEART_FULL : HEART_EMPTY}</span>`);
  }
  livesHearts.innerHTML = hearts.join("");
  const ms = nextRegenMs();
  livesTimer.textContent = ms == null ? "" : formatMs(ms);
  if (!noLivesDialog.hidden) {
    if (ms == null) nlTimer.textContent = "已恢复";
    else nlTimer.textContent = formatMs(ms);
    if (lives > 0) closeNoLivesDialog();
  }
}

function openNoLivesDialog(): void {
  noLivesDialog.hidden = false;
  renderLives();
}
function closeNoLivesDialog(): void {
  noLivesDialog.hidden = true;
}

nlAdBtn.addEventListener("click", () => {
  // Web has no rewarded ad — simulate the reward directly so the flow is
  // exercised. wxgame plugs in createRewardedVideoAd.
  addLives(1);
  closeNoLivesDialog();
  renderLives();
});
nlCloseBtn.addEventListener("click", closeNoLivesDialog);

subscribeLives(renderLives);
setInterval(renderLives, 1000);
renderLives();

buildTagChips();

if (entries.length > 0) {
  const restored =
    progress.lastKey && entries.some((e) => e.key === progress.lastKey)
      ? progress.lastKey
      : entries[0]!.key;
  selectLevel(restored);
}
resize();
